INSERT INTO marque(id, nom) VALUES (2001, 'IXS');
INSERT INTO marque(id, nom) VALUES (2002, 'SIXSIXONE');
INSERT INTO marque(id, nom) VALUES (2003, 'TSG');
INSERT INTO marque(id, nom) VALUES (2004, 'ONEAL');
INSERT INTO marque(id, nom) VALUES (2005, 'FOX');
INSERT INTO marque(id, nom) VALUES (2006, 'RACE FACE');
INSERT INTO marque(id, nom) VALUES (2007, 'POC');
INSERT INTO marque(id, nom) VALUES (2008, 'CUBE');
INSERT INTO marque(id, nom) VALUES (2009, 'ACESS');
INSERT INTO marque(id, nom) VALUES (2010, 'SERIOUS');
INSERT INTO marque(id, nom) VALUES (2011, 'KONA');
INSERT INTO marque(id, nom) VALUES (2012, 'NS BIKES');
INSERT INTO marque(id, nom) VALUES (2013, 'HAIBIKES');
INSERT INTO marque(id, nom) VALUES (2014, 'RONDO');
INSERT INTO marque(id, nom) VALUES (2015, 'ORBEA');
INSERT INTO marque(id, nom) VALUES (2016, 'CRÈME');
INSERT INTO marque(id, nom) VALUES (2017, 'DIAMANT');
INSERT INTO marque(id, nom) VALUES (2018, 'ORTLER');
INSERT INTO marque(id, nom) VALUES (2019, 'FIXIE');
INSERT INTO marque(id, nom) VALUES (2020, 'KASK');
INSERT INTO marque(id, nom) VALUES (2021, 'VOTEC');