INSERT INTO modele(id, nom) VALUES (3001, 'Flow Zip');
INSERT INTO modele(id, nom) VALUES (3002, 'Recon');
INSERT INTO modele(id, nom) VALUES (3003, 'Dermis A');
INSERT INTO modele(id, nom) VALUES (3004, 'Park FR Carbon look');
INSERT INTO modele(id, nom) VALUES (3005, 'Joint VPD System');
INSERT INTO modele(id, nom) VALUES (3006, 'Dig');
INSERT INTO modele(id, nom) VALUES (3007, 'Peewee');
INSERT INTO modele(id, nom) VALUES (3008, 'Launch Enduro');
INSERT INTO modele(id, nom) VALUES (3009, 'Indy');
INSERT INTO modele(id, nom) VALUES (3010, 'Carve Evo');
INSERT INTO modele(id, nom) VALUES (3011, 'Evo Elbow');
INSERT INTO modele(id, nom) VALUES (3012, 'Sinner');
INSERT INTO modele(id, nom) VALUES (3013, 'Rage');
INSERT INTO modele(id, nom) VALUES (3014, 'Mojito');
INSERT INTO modele(id, nom) VALUES (3015, 'Valegro');
INSERT INTO modele(id, nom) VALUES (3016, 'Manta');
INSERT INTO modele(id, nom) VALUES (3017, 'Octal');
INSERT INTO modele(id, nom) VALUES (3018, 'Access hybrid pro');
INSERT INTO modele(id, nom) VALUES (3019, 'Rockville');
INSERT INTO modele(id, nom) VALUES (3020, 'VX''s pro');
INSERT INTO modele(id, nom) VALUES (3021, 'Shoreline');
INSERT INTO modele(id, nom) VALUES (3022, 'Eight Ball');
INSERT INTO modele(id, nom) VALUES (3023, 'VM''s pro');
INSERT INTO modele(id, nom) VALUES (3024, 'Provo trail 650B');
INSERT INTO modele(id, nom) VALUES (3025, 'MT. El Captain');
INSERT INTO modele(id, nom) VALUES (3026, 'Satori');
INSERT INTO modele(id, nom) VALUES (3027, 'One');
INSERT INTO modele(id, nom) VALUES (3028, 'Zircus');
INSERT INTO modele(id, nom) VALUES (3029, 'Rove AL SE');
INSERT INTO modele(id, nom) VALUES (3030, 'Grafix pro');
INSERT INTO modele(id, nom) VALUES (3031, 'VRC Evo');
INSERT INTO modele(id, nom) VALUES (3032, 'Affair Race');
INSERT INTO modele(id, nom) VALUES (3033, 'ORDU M30');
INSERT INTO modele(id, nom) VALUES (3034, 'Rove DL');
INSERT INTO modele(id, nom) VALUES (3035, 'Café racer UNO');
INSERT INTO modele(id, nom) VALUES (3036, 'Copenhagen');
INSERT INTO modele(id, nom) VALUES (3037, 'Detroit');
INSERT INTO modele(id, nom) VALUES (3038, 'Monet');
INSERT INTO modele(id, nom) VALUES (3039, 'Blackheath');
INSERT INTO modele(id, nom) VALUES (3040, 'London One');
INSERT INTO modele(id, nom) VALUES (3041, 'Summerfie800, ld');
INSERT INTO modele(id, nom) VALUES (3042, 'Fjaril');
INSERT INTO modele(id, nom) VALUES (3043, 'Wien');